background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0

dynamic_backgound_opacity yes
background_blur 1

shell /usr/bin/zsh

url_style curly

remember_window_size no

sync_to_monitor no
