[config]
mode = "dark"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors/generated.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -SIGUSR1 cava'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-colors.vim'
output_path = '~/.config/nvim/colors/matugen.vim'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.vesktop-system24]
input_path = '~/.config/matugen/templates/system24.css'
output_path = '~/.config/vesktop/themes/system24.css'

[templates.vesktop-system24-transparent]
input_path = '~/.config/matugen/templates/system24-transparent.css'
output_path = '~/.config/vesktop/themes/system24-transparent.css'

[templates.vesktop-midnight]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.vesktop-midnight-transparent]
input_path = '~/.config/matugen/templates/midnight-discord-transparent.css'
output_path = '~/.config/vesktop/themes/midnight-discord-transparent.css'

[templates.spicetify-tui]
input_path = '~/.config/matugen/templates/spicetify-tui-colors.ini'
output_path = '~/.config/spicetify/Themes/TUI/color.ini'
post_hook = 'spicetify apply'

