[AdditionalOptions]
sidebar_config        = 0
home_config           = 1
experimental_features = 1
extensions            = noControls.js
custom_apps           = marketplace

[Patch]

[Setting]
prefs_path             = /home/jdbrannon/.config/spotify/prefs
color_scheme           = Matugen
inject_css             = 1
replace_colors         = 1
spotify_launch_flags   = --remote-debugging-port=9222|--remote-allow-origins=*
check_spicetify_update = 1
always_enable_devtools = 0
spotify_path           = /opt/spotify/
current_theme          = TUI
inject_theme_js        = 1
overwrite_assets       = 1

[Preprocesses]
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.96.518.g366879e1
with    = 2.45.1
