" Generated by matugen; see hypr/scripts/theme-switcher.sh
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

hi Normal guifg=#f0dedf guibg=#1a1112
hi NormalFloat guifg=#f0dedf guibg=#271d1e
hi Comment guifg=#9f8c8d gui=italic
hi Constant guifg=#e8c08e
hi String guifg=#e5bdbf
hi Identifier guifg=#ffb2b9
hi Function guifg=#ffb2b9 gui=bold
hi Statement guifg=#e8c08e gui=bold
hi PreProc guifg=#e5bdbf
hi Type guifg=#5d411b
hi Special guifg=#5c3f41
hi Underlined guifg=#ffb2b9 gui=underline
hi Todo guifg=#ffdad6 guibg=#93000a
hi Error guifg=#690005 guibg=#ffb4ab
hi ErrorMsg guifg=#ffb4ab
hi WarningMsg guifg=#e8c08e
hi Visual guibg=#72333b
hi CursorLine guibg=#271d1e
hi CursorLineNr guifg=#ffb2b9
hi LineNr guifg=#9f8c8d
hi StatusLine guifg=#f0dedf guibg=#271d1e
hi StatusLineNC guifg=#9f8c8d guibg=#271d1e
hi Pmenu guifg=#f0dedf guibg=#271d1e
hi PmenuSel guifg=#561d26 guibg=#ffb2b9
hi VertSplit guifg=#524344
hi WinSeparator guifg=#524344
hi SignColumn guibg=NONE
hi DiffAdd guifg=#ffddb5 guibg=#5d411b
hi DiffChange guifg=#ffdadc guibg=#5c3f41
hi DiffDelete guifg=#ffdad6 guibg=#93000a
