-- Regenerated by matugen; see hypr/scripts/theme-switcher.sh
local matugen_path = vim.fn.stdpath("config") .. "/colors/matugen.vim"

local function enable_transparency()
  local groups = {
    "Normal",
    "NormalNC",
    "NormalFloat",
    "EndOfBuffer",
    "SignColumn",
    "FloatBorder",
    "WinSeparator",
    -- neo-tree sidebar / folder view
    "NeoTreeNormal",
    "NeoTreeNormalNC",
    "NeoTreeEndOfBuffer",
    "NeoTreeWinSeparator",
    "NeoTreeStatusLine",
    "NeoTreeStatusLineNC",
    -- telescope / which-key floats, for consistency
    "TelescopeNormal",
    "TelescopeBorder",
    "WhichKeyFloat",
  }
  for _, group in ipairs(groups) do
    vim.api.nvim_set_hl(0, group, { bg = "none" })
  end
end

local function load_theme()
  if vim.uv.fs_stat(matugen_path) then
    vim.cmd.colorscheme "matugen"
  else
    vim.cmd.colorscheme "tokyonight"
  end
  enable_transparency()
end

-- Live-reload on theme-switcher runs; safe to register here since this
-- executes immediately when lazy.nvim collects plugin specs at startup.
vim.api.nvim_create_autocmd("Signal", {
  pattern = "SIGUSR1",
  callback = load_theme,
})

return {
  { "folke/tokyonight.nvim" },
  {
    -- LazyVim applies opts.colorscheme itself at the very end of its own
    -- setup(), AFTER every plugin's config() has already run. Setting a
    -- colorscheme from a plugin's own config (as we did before) gets
    -- silently overwritten by this later call — it must be set here instead.
    "LazyVim/LazyVim",
    opts = {
      colorscheme = load_theme,
    },
  },
  {
    "nvim-lualine/lualine.nvim",
    dependencies = {
      "nvim-tree/nvim-web-devicons",
    },
    opts = {
      theme = "auto",
    }
  }
}
