" Generated by matugen; see hypr/scripts/theme-switcher.sh
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

hi Normal guifg={{colors.on_surface.default.hex}} guibg={{colors.background.default.hex}}
hi NormalFloat guifg={{colors.on_surface.default.hex}} guibg={{colors.surface_container.default.hex}}
hi Comment guifg={{colors.outline.default.hex}} gui=italic
hi Constant guifg={{colors.tertiary.default.hex}}
hi String guifg={{colors.secondary.default.hex}}
hi Identifier guifg={{colors.primary.default.hex}}
hi Function guifg={{colors.primary.default.hex}} gui=bold
hi Statement guifg={{colors.tertiary.default.hex}} gui=bold
hi PreProc guifg={{colors.secondary.default.hex}}
hi Type guifg={{colors.tertiary_container.default.hex}}
hi Special guifg={{colors.secondary_container.default.hex}}
hi Underlined guifg={{colors.primary.default.hex}} gui=underline
hi Todo guifg={{colors.on_error_container.default.hex}} guibg={{colors.error_container.default.hex}}
hi Error guifg={{colors.on_error.default.hex}} guibg={{colors.error.default.hex}}
hi ErrorMsg guifg={{colors.error.default.hex}}
hi WarningMsg guifg={{colors.tertiary.default.hex}}
hi Visual guibg={{colors.primary_container.default.hex}}
hi CursorLine guibg={{colors.surface_container.default.hex}}
hi CursorLineNr guifg={{colors.primary.default.hex}}
hi LineNr guifg={{colors.outline.default.hex}}
hi StatusLine guifg={{colors.on_surface.default.hex}} guibg={{colors.surface_container.default.hex}}
hi StatusLineNC guifg={{colors.outline.default.hex}} guibg={{colors.surface_container.default.hex}}
hi Pmenu guifg={{colors.on_surface.default.hex}} guibg={{colors.surface_container.default.hex}}
hi PmenuSel guifg={{colors.on_primary.default.hex}} guibg={{colors.primary.default.hex}}
hi VertSplit guifg={{colors.outline_variant.default.hex}}
hi WinSeparator guifg={{colors.outline_variant.default.hex}}
hi SignColumn guibg=NONE
hi DiffAdd guifg={{colors.on_tertiary_container.default.hex}} guibg={{colors.tertiary_container.default.hex}}
hi DiffChange guifg={{colors.on_secondary_container.default.hex}} guibg={{colors.secondary_container.default.hex}}
hi DiffDelete guifg={{colors.on_error_container.default.hex}} guibg={{colors.error_container.default.hex}}
